name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  groupName:  
    description: 'autoscaling group name'
    required: true
  timeoutMinutes:  
    description: 'timeout in minutes'
    required: false
    default: "2"
  waitBetweenChecks:  
    description: 'Sleep time between checks in secons'
    required: false
    default: "10"    
  extraWait:  
    description: 'Sleep for extra time when runner just scaled up'
    required: false
    default: "20"
runs:
  using: 'node12'
  main: 'dist/index.js'
