name: 'AWS Autoscaler'
description: 'Scale up an EC2 instance for GitHub Runners'
inputs:
  aws-region:
    description: "GitHub Runner's AWS Region"
    required: true
  role-to-assume:
    description: "GitHub Runner's autoscaling group IAM role"
    required: true
  auto-scaling-group-name:  
    description: 'autoscaling group name'
    required: true
  timeout-minutes:  
    description: 'timeout in minutes'
    required: false
    default: "2"
  wait-between-checks:  
    description: 'Sleep time between checks in seconds'
    required: false
    default: "10"    
  extra-wait:  
    description: 'Sleep for extra time when runner just scaled up in seconds'
    required: false
    default: "60"
runs:
  using: "composite"
  steps: 
    - name: 'Configure AWS Credentials'
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: ${{ inputs.aws-region }}
        role-to-assume: ${{ inputs.role-to-assume }}
        role-skip-session-tagging: true
        # 900s/15min is minimum duration
        role-duration-seconds: 900

    - shell: bash
      env:
        GROUP_NAME: ${{ inputs.auto-scaling-group-name }}
        TIMEOUT_MINUTES: ${{ inputs.timeout-minutes }}
        WAIT_BETWEEN_CHECKS: ${{ inputs.wait-between-checks }}
        EXTRA_WAIT: ${{ inputs.extra-wait }}
      run: |
        echo "Scaled up the autoscaling group ($GROUP_NAME) to 1"
        aws autoscaling set-desired-capacity --auto-scaling-group-name $GROUP_NAME --desired-capacity 1

        secs=$TIMEOUT_MINUTES*60;
        SECONDS=0
        while (( SECONDS < secs )); do
          response=$(aws autoscaling describe-auto-scaling-groups --auto-scaling-group-names $GROUP_NAME --query 'AutoScalingGroups[0].Instances[0].LifecycleState' --output text);

          if [[ "$response" == "InService" ]]; then
            echo "Runner is in service."
            break;
          elif [[ "$response" == "Pending" ]]; then
            export extraWait=true;
          fi

          echo "Not in service yet! Wait for $WAIT_BETWEEN_CHECKS seconds.";
          sleep $WAIT_BETWEEN_CHECKS;
        done;

        if [[ $extraWait ]]; then
          echo "Wait for $EXTRA_WAIT seconds more as this runner just scaled up.";
          sleep $EXTRA_WAIT;
        fi
