name: 'Wait'
description: 'Wait a designated number of milliseconds'
inputs:
  groupName:  
    description: 'autoscaling group name'
    required: true
  timeoutMinutes:  
    description: 'timeout in minutes'
    required: false
    default: "2"
runs:
  using: 'node12'
  main: 'dist/index.js'
