name: "prepare packages"

on:
  push:

jobs:
  # unit tests
  prepare-package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Prepare packages
      run: |
        npm ci
        npm run prepare

    - name: Set Git Config
      uses: oleksiyrudenko/gha-git-credentials@v2-latest
      with:
        token: '${{ secrets.GITHUB_TOKEN }}'

    - name: Check GitHub Status
      id: check
      run: |
        if (git status | grep dist); then 
          git commit -m "Update packages" -- dist;
          echo "::set-output name=update-needed::true";
        fi
 
    - name: Push changes
      if: steps.check.outputs.update-needed
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
